services:
  wud:
    image: getwud/wud
    container_name: wud
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./store:/store
      - /home/pratikserver/docker:/docker
    environment:
      - TZ=Asia/Kathmandu
      - WUD_WATCHER_LOCAL_CRON=0 */6 * * *
      - WUD_WATCHER_LOCAL_WATCHBYDEFAULT=false
      - WUD_TRIGGER_DOCKERCOMPOSE_LOCAL_AUTO=true
      - WUD_TRIGGER_DOCKERCOMPOSE_LOCAL_FILE=/docker/portfolio/docker-compose.yml
