- name: Deploy nginx-proxy-manager
  hosts: homelab
  become: true

  vars:
    nginx_proxy_manager_path: /home/pratikserver/docker/nginx-proxy-manager

  tasks:
    - name: Check directory exists
      stat:
        path: "{{ nginx_proxy_manager_path }}"
      register: directory_register_record

    - name: Fail if directory missing
      fail:
        msg: "Nginx Proxy Manager directory not found"
      when: not directory_register_record.stat.exists

    - name: Check docker-compose.yml exists
      stat:
        path: "{{ nginx_proxy_manager_path }}/docker-compose.yml"
      register: compose_register_record

    - name: Fail if docker-compose.yml missing
      fail:
        msg: "Nginx Proxy Manager docker-compose.yml missing"
      when: not compose_register_record.stat.exists

    - name: Pull latest image
      command: docker compose pull
      args:
        chdir: "{{ nginx_proxy_manager_path }}"

    - name: Start/update container
      command: docker compose up -d
      args:
        chdir: "{{ nginx_proxy_manager_path }}"
