version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:2.14.0'
    restart: unless-stopped
    ports:
      - '80:80'   # Public HTTP
      - '81:81'   # Admin UI
      - '443:443' # Public HTTPS
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt #SSL Certificates
