services:
  portfolio-app:
    image: ghcr.io/pratikbhattarai76/portfolio-app:latest
    container_name: portfolio-app
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - docker-proxy
    labels:
      - "wud.watch=true"
      - "wud.watch.digest=true"

networks:
  docker-proxy:
    external: true
