version: '3.8'

services:
  portfolio:
    image: pratikbhattarai76/portfolio-app:1.0
    container_name: portfolio-app
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - docker-proxy

networks:
  docker-proxy:
    external: true
