# This is the second step of ansible. Here, the docker and script files are copied from my laptop into the server docker and scripts directory respectively.

- name: Sync of the infrastructure required files
  hosts: homelab
  become: true

  vars:
    local_repo_path: /home/pratik/devops/private-cloud-infrastructure
    remote_docker_path: /home/pratikserver/docker
    remote_scripts_path: /home/pratikserver/scripts

  tasks:
    - name: Ensure docker directory exists
      file:
        path: "{{ remote_docker_path }}"
        state: directory
        owner: pratikserver
        group: pratikserver
        mode: "0755"

    - name: Ensure scripts directory exists
      file:
        path: "{{ remote_scripts_path }}"
        state: directory
        owner: pratikserver
        group: pratikserver
        mode: "0755"

    - name: Copy docker directory to server
      copy:
        src: "{{ local_repo_path }}/docker/"
        dest: "{{ remote_docker_path }}/"
        owner: pratikserver
        group: pratikserver
        mode: preserve

    - name: Copy scripts directory to server
      copy:
        src: "{{ local_repo_path }}/scripts/"
        dest: "{{ remote_scripts_path }}/"
        owner: pratikserver
        group: pratikserver
        mode: preserve

    - name: Copy monitoring env file
      copy:
        src: "{{ local_repo_path }}/docker/monitoring/.env"
        dest: "{{ remote_docker_path }}/monitoring/.env"
        owner: pratikserver
        group: pratikserver
        mode: "0600"
        force: yes
      ignore_errors: true

    - name: Copy cloudflared env file
      copy:
        src: "{{ local_repo_path }}/docker/cloudflared/.env"
        dest: "{{ remote_docker_path }}/cloudflared/.env"
        owner: pratikserver
        group: pratikserver
        mode: "0600"
        force: yes
      ignore_errors: true

    - name: Copy nextcloud env file
      copy:
        src: "{{ local_repo_path }}/docker/nextcloud/.env"
        dest: "{{ remote_docker_path }}/nextcloud/.env"
        owner: pratikserver
        group: pratikserver
        mode: "0600"
        force: yes
      ignore_errors: true

    - name: Copy portfolio env file
      copy:
        src: "{{ local_repo_path }}/docker/portfolio/.env"
        dest: "{{ remote_docker_path }}/portfolio/.env"
        owner: pratikserver
        group: pratikserver
        mode: "0600"
        force: yes
      ignore_errors: true

    - name: Ensure portfolio bash script is executable
      file:
        path: "{{ remote_scripts_path }}/update-portfolio.sh"
        mode: "0755"
      ignore_errors: true
