# Here, where my IP is defined for using all of the .yml files.

[homelab]
# For home LAN IP
local ansible_host=192.168.1.250 ansible_user=pratikserver ansible_ssh_private_key_file=/home/pratik/.ssh/id_ed25519
# For tailscale VPN IP
tailscale ansible_host=100.93.150.69 ansible_user=pratikserver ansible_ssh_private_key_file=/home/pratik/.ssh/id_ed25519
