[homelab]
local ansible_host=192.168.1.250 ansible_user=pratikserver ansible_ssh_private_key_file=/home/pratik/.ssh/id_ed25519
tailscale ansible_host=100.93.150.69 ansible_user=pratikserver ansible_ssh_private_key_file=/home/pratik/.ssh/id_ed25519
aws ansible_host=3.6.37.254 ansible_user=ubuntu ansible_ssh_private_key_file=/home/pratik/.ssh/aws-key.pem
