services:
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:2026.3.0
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    networks:
      - docker-cloudflared

networks:
  docker-cloudflared:
    external: true
