services:
  nextcloud-db:
    image: mariadb:12.2.2-noble
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=nextcloud
      - MARIADB_USER=nextcloud
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    mem_limit: 2g
    cpus: 2.0
    networks:
      - docker-proxy

  nextcloud-app:
    image: nextcloud:33.0.2-apache
    container_name: nextcloud-app
    restart: unless-stopped
    depends_on:
      nextcloud-db:
        condition: service_healthy
    volumes:
      - ./nextcloud-config:/var/www/html
      - /mnt/storage/Photos/Pictures:/var/www/html/data/${NC_ADMIN_USER}/files/Pictures
    environment:
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - NEXTCLOUD_ADMIN_USER=${NC_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NC_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NC_TRUSTED_DOMAIN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/status.php"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    mem_limit: 2g
    cpu_limit: 2.0
    networks:
      - docker-proxy

networks:
  docker-proxy:
    external: true
