services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:1.35.4-alpine
    restart: unless-stopped
    environment:
      - SIGNUPS_ALLOWED=false
      - DOMAIN=https://vault.pratik-labs.xyz
    volumes:
      - ./vw-data:/data
    networks:
      - docker-proxy

networks:
  docker-proxy:
    external: true
